import React,{useState} from 'react';
import {Button,Icon,Empty,date,timer} from './ui.jsx';
import {library,stats,score} from './domain.js';
export {Setup,Profile} from './Setup.jsx';
export {default as Results} from './Results.jsx';
export function PageHeading({eyebrow,title,text}){return <div className="page-heading">{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{text && <p>{text}</p>}</div>;}
export function LibraryCard({item,onSelect}){return <button className="library-card card" onClick={onSelect}><div className="row between"><span className={`tile ${item.color}`}><Icon name={item.icon} size={23}/></span><span className="tag">{item.industry}</span></div><h3>{item.role}</h3><p>{item.description}</p><div className="card-bottom"><span><Icon name="clock" size={15}/> 15 phút · 3 mức độ</span><Icon name="arrow" size={19}/></div></button>;}
export function ProgressChart({sessions,illustration=false}){
  const points=illustration?[5.2,5.9,5.5,7,6.6,7.8,8.4]:sessions.filter(s=>s.completedAt && score(s)!==null).slice(0,7).reverse().map(score);
  if(!points.length)return <Empty icon="chart" title="Tiến bộ bắt đầu từ buổi đầu tiên">Hoàn thành buổi luyện để xem biểu đồ điểm của bạn.</Empty>;
  const coordinates=points.map((p,i)=>`${30+i*(300/Math.max(1,points.length-1))},${135-p*11}`).join(' ');
  return <div className="chart"><svg viewBox="0 0 360 165" role="img" aria-label={illustration?'Biểu đồ điểm minh họa':`Điểm các buổi luyện: ${points.join(', ')}`}><defs><linearGradient id={illustration?'chart-demo':'chart-live'} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7460e8" stopOpacity=".2"/><stop offset="100%" stopColor="#7460e8" stopOpacity="0"/></linearGradient></defs>{[0,5,10].map(v=><g key={v}><line x1="30" x2="335" y1={135-v*11} y2={135-v*11} stroke="#e9e8f0" strokeDasharray="4 4"/><text x="4" y={139-v*11}>{v}</text></g>)}<polygon points={`30,135 ${coordinates} ${points.length>1?330:30},135`} fill={`url(#${illustration?'chart-demo':'chart-live'})`}/><polyline points={coordinates} fill="none" stroke="#7560dc" strokeWidth="3" strokeLinejoin="round"/>{points.map((p,i)=><g key={i}><circle cx={30+i*(300/Math.max(1,points.length-1))} cy={135-p*11} r="4" fill="#7560dc" stroke="white" strokeWidth="2"/><text x={30+i*(300/Math.max(1,points.length-1))} y="158" textAnchor="middle">Lần {i+1}</text></g>)}</svg></div>;
}
export function History({sessions,onSelect,onStart}){return <section className="card history-card">{!sessions.length?<Empty title="Hành trình của bạn bắt đầu tại đây" action={<Button kind="secondary" onClick={onStart}>Luyện buổi đầu tiên <Icon name="arrow" size={16}/></Button>}>Các buổi luyện sẽ được lưu tự động trên thiết bị này.</Empty>:<div className="table-scroll"><table><thead><tr><th>Vị trí phỏng vấn</th><th>Ngày luyện</th><th>Thời gian</th><th>Điểm số</th><th>Trạng thái</th><th><span className="sr-only">Thao tác</span></th></tr></thead><tbody>{sessions.map(s=><tr key={s.id}><td><strong>{s.setup.role}</strong><small>{s.setup.industry}</small></td><td>{date(s.startedAt)}</td><td>{timer(s.durationSeconds || 0)}</td><td><strong className="score-text">{score(s)===null?'—':`${score(s)}/10`}</strong></td><td><span className={`pill ${s.evaluation?'green':''}`}>{s.evaluation?'Đã hoàn thành':s.completedAt?'Chờ đánh giá':'Đang luyện'}</span></td><td><button className="text-button" onClick={()=>onSelect(s)}>{s.completedAt?'Xem kết quả':'Tiếp tục'} <Icon name="arrow" size={16}/></button></td></tr>)}</tbody></table></div>}</section>;}
export function Dashboard({memberName,sessions,setup,startSetup,go,selectSession}){
  const metrics=stats(sessions);
  return <><div className="page-heading row between wrap"><div><span className="eyebrow">MỖI NGÀY MỘT BƯỚC TIẾN</span><h1>Chào {memberName}, sẵn sàng tỏa sáng?</h1><p>Một buổi luyện hôm nay. Một cơ hội tốt hơn ngày mai.</p></div><Button icon="plus" onClick={()=>startSetup()}>Bắt đầu phỏng vấn</Button></div><div className="stats-grid">{[['Buổi đã luyện',metrics.count,'book','purple'],['Điểm trung bình',metrics.average,'medal','mint'],['Phút luyện tập',metrics.minutes,'clock','peach'],['Ngày liên tiếp',metrics.streak,'flame','yellow']].map(([label,value,icon,color])=><div className="stat card" key={label}><span className={`tile ${color}`}><Icon name={icon}/></span><span>{label}</span><strong>{value}{label==='Điểm trung bình' && <small>/10</small>}</strong></div>)}</div><div className="dashboard-grid"><section className="practice-banner"><span className="pill">DÀNH CHO BẠN</span><h2>Cơ hội tiếp theo.<br/>Phiên bản tự tin hơn.</h2><p>Luyện câu hỏi sát vị trí mục tiêu và nhận<br className="desktop-only"/> góp ý cụ thể sau mỗi câu trả lời.</p><Button kind="white" icon="arrow" onClick={()=>startSetup(library.find(p=>p.industry===setup.industry) || library[3])}>Luyện phỏng vấn ngay</Button><div className="banner-orbit"><Icon name="mic" size={65}/></div></section><section className="card"><div className="section-heading"><div><h3>Tiến bộ của bạn</h3><p>Điểm các buổi luyện gần nhất</p></div><Icon name="chart"/></div><ProgressChart sessions={sessions}/></section></div><div className="section-heading"><div><h2>Khám phá buổi phỏng vấn</h2><p>Chọn lĩnh vực bạn muốn chinh phục.</p></div><button className="text-button" onClick={()=>go('library')}>Xem thư viện <Icon name="arrow" size={17}/></button></div><div className="library-grid">{library.slice(0,3).map(item=><LibraryCard key={item.id} item={item} onSelect={()=>startSetup(item)}/>)}</div><div className="section-heading"><h2>Lịch sử gần đây</h2><button className="text-button" onClick={()=>go('history')}>Xem tất cả <Icon name="arrow" size={17}/></button></div><History sessions={sessions.slice(0,3)} onSelect={selectSession} onStart={()=>startSetup()}/></>;
}
export function Library({startSetup}){
  const [filter,setFilter]=useState('Tất cả'),[search,setSearch]=useState('');
  const matches=library.filter(item=>(filter==='Tất cả'||item.category===filter)&&`${item.role} ${item.industry}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')));
  return <><PageHeading eyebrow="TÌM BUỔI LUYỆN PHÙ HỢP" title="Thư viện phỏng vấn" text="Từ buổi phỏng vấn đầu tiên đến bước tiến tiếp theo trong sự nghiệp."/><div className="library-tools"><div className="tabs">{['Tất cả','Logistics','Marketing','Finance','IT','Business'].map(item=><button key={item} onClick={()=>setFilter(item)} className={filter===item?'active':''}>{item==='Finance'?'Tài chính':item==='Business'?'Kinh doanh':item}</button>)}</div><label className="search"><Icon name="search"/><input aria-label="Tìm vị trí phỏng vấn" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm vị trí phỏng vấn…"/></label></div><div className="library-grid">{matches.map(item=><LibraryCard key={item.id} item={item} onSelect={()=>startSetup(item)}/>)}</div>{!matches.length && <Empty title="Chưa tìm thấy vị trí phù hợp" action={<Button onClick={()=>startSetup()}>Tạo buổi phỏng vấn riêng</Button>}>Thử từ khóa khác hoặc tự tạo vị trí của bạn.</Empty>}</>;
}
export function Settings({account,onAuth,onReset}){return <><PageHeading title="Cài đặt" text="Quản lý trải nghiệm và dữ liệu của bạn."/><section className="card settings-card"><span className="tile mint"><Icon name="lock"/></span><h2>Dữ liệu của bạn, trên thiết bị của bạn</h2><p>Lịch sử, bản ghi hội thoại, nhận xét và CV được lưu trong trình duyệt này. Dữ liệu có thể mất khi bạn xóa bộ nhớ trình duyệt hoặc dùng chế độ ẩn danh. Chưa có đồng bộ hay khôi phục trên thiết bị khác trong bản thử nghiệm.</p><p>Khi phỏng vấn, nội dung hồ sơ, CV và câu trả lời được gửi đến OpenAI để tạo câu hỏi và đánh giá. Tệp CV được đọc qua máy chủ và không lưu trên máy chủ.</p><div className="setting-row"><div><strong>Ngôn ngữ giao diện</strong><p>Tiếng Việt</p></div><span className="pill">VI</span></div><div className="setting-row"><div><strong>Tài khoản và đồng bộ</strong><p>{account?'Tài khoản mô phỏng đang hoạt động. Đồng bộ đám mây chưa được triển khai.':'Bạn đang sử dụng chế độ khách.'}</p></div>{!account && <Button kind="secondary" onClick={onAuth}>Tạo tài khoản miễn phí</Button>}</div><div className="setting-row"><div><strong>Xóa dữ liệu InterviewAI</strong><p>Xóa hồ sơ, CV, lịch sử, tài khoản và gói mô phỏng trên thiết bị. Không thể hoàn tác.</p></div><Button kind="danger-soft" onClick={onReset}>Xóa toàn bộ dữ liệu</Button></div></section></>;}
