import React,{useState} from 'react';
import {Brand,Button,Icon,Field,ErrorNote} from './ui.jsx';
import {plans} from './domain.js';
import {ProgressChart,PageHeading} from './Pages.jsx';

export function Pricing({choosePlan,current,compact=false}){return <section className="pricing" id="pricing">{!compact && <div className="center section-heading"><span className="eyebrow">ĐẦU TƯ CHO CHÍNH BẠN</span><h2>Một bước nhỏ cho cơ hội lớn</h2><p>Bắt đầu miễn phí. Nâng cấp khi bạn sẵn sàng.</p></div>}<div className="pricing-grid">{plans.map(plan=><article key={plan.name} className={`plan card ${plan.name==='Premium'?'featured':''}`}>{plan.name==='Premium' && <span className="popular">LỰA CHỌN NỔI BẬT</span>}<h3>{plan.name}</h3><p>{plan.description}</p><div className="price">{plan.price}<span> VNĐ<br/><small>/ tháng</small></span></div><Button kind={plan.name==='Premium'?'primary':'secondary'} disabled={current===plan.name} onClick={()=>choosePlan(plan.name)}>{current===plan.name?'Gói hiện tại':plan.name==='Free'?'Bắt đầu miễn phí':`Chọn ${plan.name}`}</Button><ul>{plan.features.map(f=><li key={f}><Icon name="check" size={17}/>{f}</li>)}</ul></article>)}</div><p className="pricing-note"><Icon name="lock" size={15}/> Bảng giá và nâng cấp được mô phỏng trong bản thử nghiệm. Không thu tiền thật. Mức chi tiết báo cáo áp dụng theo gói lúc bắt đầu buổi luyện.</p></section>;}
export function Home({entry,go,choosePlan}){return <>
  <section className="hero"><div className="hero-copy"><span className="hero-badge"><i/> NGƯỜI ĐỒNG HÀNH SỰ NGHIỆP CỦA BẠN</span><h1>Phỏng vấn tự tin.<br/><em>Nắm bắt cơ hội.</em></h1><p>Luyện phỏng vấn cùng AI, nhận góp ý dành riêng cho bạn và nhìn thấy mình tiến bộ sau mỗi buổi luyện.</p><div className="row wrap"><Button onClick={entry}>Bắt đầu phỏng vấn miễn phí <Icon name="arrow" size={18}/></Button><button className="text-button" onClick={()=>document.getElementById('how')?.scrollIntoView({behavior:'smooth'})}><Icon name="play" size={16}/> Xem cách hoạt động</button></div><div className="hero-checks"><span><Icon name="check" size={15}/> Không cần thẻ thanh toán</span><span><Icon name="check" size={15}/> Có thể dùng không cần tài khoản</span></div></div><div className="hero-preview"><div className="preview-top"><Brand onClick={()=>go('home')}/><span className="pill">Xem trước giao diện</span></div><div className="preview-interview"><div className="mini-orb"><Icon size={35}/></div><span className="pill">Người phỏng vấn AI</span><h3>Hãy kể về một thử thách bạn đã vượt qua trong công việc.</h3><div className="sound-wave">{Array.from({length:23},(_,i)=><i key={i} style={{height:`${12+(Math.sin(i*1.2)+1)*15}px`}}/>)}</div><span className="muted tiny">Không gian để bạn thử, học và tiến bộ.</span></div><div className="preview-feedback"><span className="tile mint"><Icon name="chart"/></span><div><strong>Mỗi lần luyện, một bước tiến</strong><p>Nhận xét cụ thể · Lộ trình rõ ràng</p></div><Icon name="check"/></div><span className="floating-star">✦</span></div></section>
  <section className="industries"><span>SẴN SÀNG CHO NHIỀU LĨNH VỰC</span><div>Logistics <i>✦</i> Marketing <i>✦</i> Tài chính <i>✦</i> Công nghệ <i>✦</i> Kinh doanh</div></section>
  <section id="features" className="public-section"><div className="section-heading center"><span className="eyebrow">LUYỆN TẬP CÓ ĐỊNH HƯỚNG</span><h2>Không chỉ trả lời. Hiểu cách làm tốt hơn.</h2><p>Một không gian đáng tin cậy để chuẩn bị cho các cuộc gặp mặt quan trọng</p></div><div className="features-grid">{[['mic','purple','Trò chuyện cùng AI','Câu hỏi linh hoạt theo vị trí, CV và chính câu trả lời của bạn. Luyện bằng giọng nói hoặc văn bản.'],['spark','mint','Góp ý để tiến bộ','Hiểu điểm mạnh, điều cần cải thiện và cách diễn đạt câu trả lời tốt hơn.'],['chart','peach','Thấy rõ hành trình','Lưu lại từng buổi luyện, theo dõi điểm số và tiếp tục ngay nơi bạn đã dừng.']].map(([icon,color,title,desc])=><article className="feature card" key={title}><span className={`tile ${color}`}><Icon name={icon}/></span><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
  <section className="how-section public-section" id="how"><div><span className="eyebrow">ĐƠN GIẢN ĐỂ BẮT ĐẦU</span><h2>Từ chuẩn bị<br/>đến sẵn sàng.</h2><p>Chỉ cần một mục tiêu.<br/>InterviewAI sẽ đồng hành cùng bạn.</p><Button onClick={entry}>Thử ngay miễn phí <Icon name="arrow" size={17}/></Button></div><div className="steps-list">{[['01','Chọn mục tiêu của bạn','Tải CV, chọn vị trí và tùy chỉnh buổi luyện tập.'],['02','Phỏng vấn với AI','Trả lời từng câu hỏi bằng giọng nói hoặc nhập văn bản.'],['03','Nhận góp ý và luyện tiếp','Xem đánh giá chi tiết, rút kinh nghiệm và theo dõi tiến bộ.']].map(([n,title,desc])=><div key={n}><span>{n}</span><div><h3>{title}</h3><p>{desc}</p></div></div>)}</div></section>
  <section className="public-section demo-section"><div><span className="eyebrow">MỖI BUỔI LUYỆN ĐỀU CÓ Ý NGHĨA</span><h2>Nhìn thấy sự tiến bộ.<br/>Cảm nhận sự tự tin.</h2><p>Tổng quan điểm số và gợi ý cho các buổi luyện tập tiếp theo trong một không gian.</p><button className="text-button" onClick={()=>go('dashboard')}>Khám phá Tổng quan <Icon name="arrow" size={17}/></button></div><div className="card demo-chart"><div className="row between"><h3>Hành trình tiến bộ</h3><span className="pill">Dữ liệu minh họa</span></div><ProgressChart illustration sessions={[]}/></div></section>
  <section className="public-section"><div className="section-heading center"><span className="eyebrow">CÂU CHUYỆN LUYỆN TẬP</span><h2>Thêm tự tin mỗi ngày</h2><p></p></div><div className="reviews">{[['Minh Anh','Ứng viên Marketing','Tôi biết mình cần thêm ví dụ và số liệu thay vì chỉ nói chung chung về kinh nghiệm.'],['Quang Huy','Lập trình viên','Có một nơi để tập nói về dự án giúp tôi sắp xếp lại suy nghĩ trước buổi phỏng vấn.'],['Thu Hà','Sinh viên mới tốt nghiệp','Bắt đầu không cần tài khoản giúp việc bắn đầu thuận tiện hơn rất nhiều']].map(([name,role,quote])=><div className="card review" key={name}><span className="stars">★★★★★</span><p>“{quote}”</p><div className="row"><span className="avatar">{name.charAt(0)}</span><div><strong>{name}</strong><small>{role} </small></div></div></div>)}</div></section>
  <div className="public-section"><Pricing choosePlan={choosePlan}/></div>
  <section className="public-section faq"><div><span className="eyebrow">GIẢI ĐÁP THẮC MẮC</span><h2>Trước khi bạn bắt đầu</h2></div><div>{[['Tôi có cần tạo tài khoản không?','Không. Bạn có thể tải CV, phỏng vấn và xem kết quả bằng chế độ khách. Tài khoản trong bản thử nghiệm được mô phỏng trên thiết bị.'],['Dữ liệu của tôi được lưu ở đâu?','Hồ sơ, CV và lịch sử được lưu trong trình duyệt này. Dữ liệu có thể mất khi xóa bộ nhớ hoặc dùng chế độ ẩn danh. Nội dung cần thiết được gửi đến OpenAI khi dùng tính năng AI.'],['Tôi có thể luyện bằng tiếng Anh không?','Có. Hãy chọn tiếng Anh trong bước cài đặt phỏng vấn hoặc chọn buổi luyện tiếng Anh từ thư viện.'],['Tôi có thể thay đổi độ khó cho phù hợp với trình độ của mình không','Có thể, nền tảng của chúng tôi cho phép người dùng tùy chỉnh độ khó của phiên phỏng vấn sao cho phù hợp']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="final-cta"><span className="eyebrow">CƠ HỘI ĐANG Ở PHÍA TRƯỚC</span><h2>Sẵn sàng để luyện tập?</h2><p>Bắt đầu từ một buổi luyện. Tạo nên sự khác biệt cho chính bạn.</p><Button kind="white" onClick={entry}>Bắt đầu phỏng vấn miễn phí <Icon name="arrow" size={17}/></Button></section>
</>;}
export function Auth({mode,account,onAuth,onGuest,onSwitch}){
  const [name,setName]=useState(''),[email,setEmail]=useState(''),[error,setError]=useState('');
  function submit(e){e.preventDefault();setError('');if(mode==='login'){if(!account || account.email.toLowerCase()!==email.trim().toLowerCase()){setError('Chưa có tài khoản mô phỏng với email này trên thiết bị. Hãy tạo tài khoản hoặc tiếp tục với tư cách khách.');return;}onAuth(account);}else onAuth({name:name.trim(),email:email.trim()});}
  return <div className="auth-layout"><div className="auth-story"><span className="eyebrow">MỘT BƯỚC ĐẾN GẦN CƠ HỘI</span><h1>Sự tự tin<br/> đến từ chuẩn bị.</h1><p>Luyện tập theo nhịp của bạn, với một người đồng hành luôn sẵn sàng lắng nghe.</p><div className="auth-orb"><Icon name="spark" size={85}/></div></div><section className="auth-card card"><span className="tile purple"><Icon name="user"/></span><h2>{mode==='register'?'Bắt đầu hành trình của bạn':'Chào mừng bạn trở lại'}</h2><p>{mode==='register'?'Tạo tài khoản miễn phí để trải nghiệm luồng nâng cấp.':'Truy cập tài khoản mô phỏng đã tạo trên thiết bị này.'}</p><div className="notice tiny">Tài khoản thử nghiệm, chưa có xác thực hay đồng bộ đám mây. Không cần mật khẩu.</div><form onSubmit={submit}>{mode==='register' && <Field label="Tên của bạn"><input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Nhập tên của bạn"/></Field>}<Field label="Email"><input required type="email" maxLength={200} value={email} onChange={e=>setEmail(e.target.value)} placeholder="ban@example.com"/></Field><ErrorNote>{error}</ErrorNote><Button disabled={mode==='register'&&!name.trim()}>{mode==='register'?'Tạo tài khoản miễn phí':'Đăng nhập'} <Icon name="arrow" size={17}/></Button></form><div className="divider"><span>hoặc trải nghiệm ngay</span></div><Button kind="secondary" onClick={onGuest}>Tiếp tục không cần tài khoản</Button><p className="center tiny">{mode==='register'?'Đã có tài khoản?':'Chưa có tài khoản?'} <button className="text-button" onClick={onSwitch}>{mode==='register'?'Đăng nhập':'Đăng ký miễn phí'}</button></p></section></div>;
}
export function Checkout({plan,account,onBack,onSuccess}){const[accepted,setAccepted]=useState(false);return <div className="checkout"><PageHeading title="Sẵn sàng cho bước tiến mới" text="Hoàn tất nâng cấp gói dịch vụ của bạn."/><div className="checkout-grid"><section className="card"><span className="tile purple"><Icon name="lock"/></span><h2>Thanh toán</h2><p>Đây là phiên bản thử nghiệm. Không yêu cầu thẻ ngân hàng và không thu tiền thật.</p><div className="checkout-account"><strong>{account.name}</strong><span>{account.email}</span></div><label className="checkbox"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>Tôi đã đọc và đồng ý với chính sách của interviewAI.</label><Button disabled={!accepted} onClick={onSuccess}>Thanh toán giả lập · {plan.price} VNĐ</Button><button className="text-button" onClick={onBack}>Quay lại chọn gói</button></section><aside className="card"><span className="eyebrow">TÓM TẮT GÓI DỊCH VỤ</span><h2>InterviewAI {plan.name}</h2><p>{plan.description}</p><ul>{plan.features.map(f=><li key={f}><Icon name="check" size={17}/>{f}</li>)}</ul><div className="checkout-total"><span>Tổng cộng / tháng</span><strong>{plan.price} VNĐ</strong></div><small>Tự động gia hạn hàng tháng.</small></aside></div></div>;}
